### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by sshivaji**
Hi,

I have done a bunch of things to improve the UI look and feel along with misc things. I authored kivy-chess in the past (https://github.com/sshivaji/kivy-chess). However, after looking over your code, I much prefer PYQT4 and its widgets. 

I have a bunch of things in my roadmap, mainly to bring up large database position search with custom search text (this works well in kivy chess and my web solution too). For example on Kivy chess, I support searches like what are the top games of Magnus carlsen after 1.e4 c5 2. Nf3 d6 3. Bb5+ where his opponent's rating is more than 2700.

I can also do DGT board support (from picochess, where I am also a co-author). DGT support also works in kivy-chess.

Anyway, take a look at my fork and merge as you please. Feel free to contact me anytime.

Thanks!, Shiv

### CODE REVIEW

**Comment by sshivaji** [comment]
One thing I realize, I removed coordinates display, this should probably be an option. However, for serious chess players, I think coordinates are annoying, I know coordinates by heart for a long time.. :)

**Comment by asdfjkl** [comment]
First of all, thanx! I'll look into this and will try to merge things as soon as possible. Note that I am currently rewriting version 3.0 in C++/Qt (due to various issues with python), so please have some patience :-)

**Comment by sshivaji** [comment]
I am making some small improvements as we speak.

I am concerned about moving to C++ as python is easier to develop than C++
at least for me, are you sure you want to do this? :)

**Comment by asdfjkl** [comment]
Yes, I see the future definitely in C++/Qt. This has to do mainly with deployment, but also other issues. I wrote about the reasons here https://buildingjerry.wordpress.com/2015/12/16/next-steps-c/ 
Note that I found that writing in Qt-flavored, modern C++ is actually not that hard compared to python, but  you gain a lot by static typing, imho...

**Comment by sshivaji** [comment]
I see. I might help maintain the python fork then. I prefer python for my dev at least.

PYQT is def a step above Kivy (another framework I played with), at least QT's widgets are available.

**Comment by sshivaji** [comment]
One question to ask on your highlight. Rather than using offsets, it seems
easier to make every move reachable via fen (to respond to click to move).
With custom fonts and sizes like I am using, the offset calculation seems
wrong for large games. Do you have more information on this?

I am tempted to re-write this layer to include a fen for every move, so
that click on move can be done without offsets.

Shiv

**Comment by sshivaji** [comment]
Also, what is your email address, it might be easier to touch base by
email, mine is sshivaji at gmail.com

**Comment by asdfjkl** [comment]
sorry about not replying. currently quite busy. will come back to you asap.

**Comment by sshivaji** [comment]
After playing with pyqt a bit, I am disappointed that anchor support is not as good as expected. You cannot easily go to anchor for example. I fixed the jumping to positions but I notice that even in your initial python version, jumping to positions does not work well (I tried with large and messy files).

At this point, I think I will call it quits and get back to https://github.com/sshivaji/kivy-chess. PyQT is not bad, but somehow I run into problems with anchors and jumping that I should not run into, QTextEdit should provide more api such as jump to anchor.. I will look at your C++ implementation and might contribute back on a later date. Feel free to withdraw/close this pull request.

**Comment by asdfjkl** [comment]
I am closing this. I am focusing my work on version 3. There, I have implemented your GUI patches. I will also add the encoding detection in future version.

**Pull request closed without merging**
