### PR TITLE
Removed checked in target directory.

### PR DESCRIPTION
**Pull request by mipper**
This directory is automatically created and populated by maven and should not be checked in.

Looks like the has been tried before but may not have worked as the files are still present in the remote repo.

### CODE REVIEW

**Comment by asdfjkl** [comment]
Thanks for your contribution! But could you help me by describing briefly what happened in "Encapsulate UCI engine."? Bugfixes?

**Comment by asdfjkl** [comment]
I do appreciate your effort in rewriting the engine-code, but i am rejecting this. I will handpick changes from your code. But right now, after reverting to this I get when I stop an already running engine:

java.io.IOException: Die Pipe wird gerade geschlossen (pipe is currently closing)
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:347)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:327)
	at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:159)
	at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:251)
	at java.base/java.io.BufferedWriter.flush(BufferedWriter.java:257)
	at org.asdfjkl.jerryfx.gui.UciEngineProcess.send(UciEngineProcess.java:30)
	at org.asdfjkl.jerryfx.gui.EngineThread.processCommand(EngineThread.java:191)
	at org.asdfjkl.jerryfx.gui.EngineThread.serviceQueue(EngineThread.java:106)
	at org.asdfjkl.jerryfx.gui.EngineThread.run(EngineThread.java:76)

**Comment by mipper** [comment]
Apologies - I wasn't supposed to have pushed the re-encapsulation code; that wasn't finished.  The PR was only supposed to be for removing the target directory which is totally generated by maven during a build.  If there's stuff I pushed by accident that you find useful, obviously, help youself.

**Comment by asdfjkl** [comment]
Thanks for the reply! Looking at the changes, I already removed target dir, thx for spotting!

**Pull request closed without merging**
